/* eslint-disable @typescript-eslint/naming-convention */
export enum ENUM_AUTH_ACTION {
	AUTH_LOGIN = 'AUTH_LOGIN',
	AUTH_SIGN_UP = 'AUTH_SIGN_UP',
	AUTH_AUTHENTICATED_SUCCESS = 'AUTH_AUTHENTICATED_SUCCESS',
	AUTH_AUTHENTICATED_FAIL = 'AUTH_AUTHENTICATED_FAIL',
}

export enum ENUM_CATEGORY_ACTION {
	CATEGORY_SELECTED = 'CATEGORY_SELECTED',
}
