/* eslint-disable @typescript-eslint/naming-convention */
export enum ENUM_AUTH_ACTION {
	AUTH_LOGIN = 'AUTH_LOGIN',
	AUTH_SIGN_UP = 'AUTH_SIGN_UP',
	AUTH_AUTHENTICATED_SUCCESS = 'AUTH_AUTHENTICATED_SUCCESS',
	AUTH_AUTHENTICATED_FAIL = 'AUTH_AUTHENTICATED_FAIL',
}

export enum ENUM_CATEGORY_ACTION {
	SET_CATEGORY = 'SET_CATEGORY',
	GET_CATEGORY = 'GET_CATEGORY',
	CATEGORY_SELECTED = 'CATEGORY_SELECTED',
}

export enum ENUM_CART_ACTION {
	ADD_TO_CART = 'ADD_TO_CART',
	SET_TO_CART = 'SET_TO_CART',
	REMOVE_FROM_CART = 'REMOVE_FROM_CART',
	REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART',
	LOAD_CART_FROM_LOCAL_STORAGE = 'LOAD_CART_FROM_LOCAL_STORAGE',
}

export enum ENUM_ORDER_ACTION {
	UPDATE_RECEIVER_INFO = 'UPDATE_RECEIVER_INFO',
}

export enum ENUM_SHARE_ACTION {
  UPDATE_SHARE_DATA = 'UPDATE_SHARE_DATA',
}
